[ci] Fix missing imports
Error:
- src/main.cpp:6:10: fatal error: OCC/core/core.h: No such file or directory
    #include "OCC/core/core.h"
- src/main.cpp:15:12: fatal error: se050_middleware.h: No such file or directory
    #include "se050_middleware.h"

Signed-off-by: Julian Strobl <jmastr@mailbox.org>